03-03-main-page: add main page layout
js-tasks-ru/htmlcss-20220811_konstantin87 pull request #5
Opened 2022-08-27 16:32 UTC by izba

2022-08-27 16:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-29 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-29 20:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-30 14:19 UTC, GSemikozov requested changes

2022-08-30 14:19 UTC, GSemikozov commented on components/modern-normalize.css
> +/*! modern-normalize v1.1.0 | MIT License | https://github.com/sindresorhus/modern-normalize */
это не компонент, можно положить рядом с main.css

2022-08-30 14:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 14:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-30 16:51 UTC, GSemikozov approved these changes

2022-08-30 16:51 UTC, merged